#!/usr/bin/env ruby
require_relative 'cohort'
require_relative 'parser'
require_relative 'group_generator'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: runner.rb [-f path]"

  opts.on("-f", "--filename PATH", "Specify PATH to the file with people and history. Looks in pairdata.txt by default.") do |f|
    options[:filename] = f
  end

  opts.on("-u", "--update", "Updates the file with the generated pairs after running.") do
    options[:update] = true
  end

  opts.on("-g", "--group_size SIZE", "Size of groups to generate. Not yet implemented") do |g|
    options[:group_size] = g
  end
end.parse!

options[:filename]   ||= "pairdata.txt"
options[:update]       ||= false
options[:group_size] ||= 2

args = PairParser.load_file(options[:filename])
args[:size] = options[:group_size]
generator = Cohort.new(args)
generator.next_groups(options[:update]).each { |group| puts group.map(&:to_s).join(", ") }

PairParser.save_file(options[:filename], generator)
